name: Java CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test
        run: | 
          echo "Building and testing it"
  deploy-tst:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to TST
        run: |
          echo "Deploying to Test"
  e2e-tests:
    needs: deploy-tst
    runs-on: ubuntu-latest

    steps:
      - name: Run E2E Tests
        run: |
          echo "Building and testing it"
  sonarqube-analysis:
    needs: e2e-tests
    runs-on: ubuntu-latest

    steps:
      - name: SonarQube Analysis
        run: |
          echo "Run Sonar Qube Analysis"
  deploy-prod:
    needs: sonarqube-analysis
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to prod"
      - name: Notify the team about deployment
        uses: dragos-cojocari/ms-teams-notification@v1.0.2
        if: success()
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.TEAMS }}
          notification-summary: "Deployment for ${{ github.repository }} succeeded."
          notification-color: 28a745
          timezone: Europe/Amsterdam
